.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_demop_800DD4F0

dlabel D_demop_800DD4F0
    /* 0 800DD4F0 04000000 */ .word 0x00000004
enddlabel D_demop_800DD4F0

.align 2
nonmatching D_demop_800DD4F4

dlabel D_demop_800DD4F4
    /* 4 800DD4F4 */ .asciz ":ACCEPT"
    /* 3A41434345505400 */
.align 2
enddlabel D_demop_800DD4F4

.align 2
nonmatching D_demop_800DD4FC

dlabel D_demop_800DD4FC
    /* C 800DD4FC */ .asciz ":BACK"
    /* 3A4241434B000000 */
.align 2
.align 2
    /* 14 800DD504 */ .asciz "TUTORIAL"
    /* 5455544F5249414C00000000 */
.align 2
.align 2
    /* 20 800DD510 */ .asciz "OPENING"
    /* 4F50454E494E4700 */
.align 2
enddlabel D_demop_800DD4FC
