#!/usr/bin/env python3
"""Generate splat overlay configs for DATA.BIN packages from codemap.json.

Reads decomp/configs/USA/overlays/codemap.json (written by
decomp/tools/extract_packages.py), renders overlay.template.yaml into
configs/USA/overlays/<name>.yaml, and rewrites the overlays.toml
manifest. Both are committed; re-run via decomp/tools/extract_packages.sh
after changing the code map or the template.
"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OVERLAYS = os.path.join(REPO, "decomp", "configs", "USA", "overlays")
TEMPLATE = os.path.join(OVERLAYS, "overlay.template.yaml")

TITLES = {
    **{f"p{i:02d}": f"P{i:02d} mission package part2 (DATA.BIN slot {i})" for i in range(28)},
    **{f"a{i:02d}": f"A{i:02d} mission package part2 (DATA.BIN slot {32 + i})" for i in range(4)},
    "demop": "DEMOP demo package part2 (D_800AC31C)",
    "endingp": "ENDINGP ending package part2 (D_800AC340)",
    "arenap": "ARENAP battle-arena package part2 (D_800AC364)",
}


def subsegments(e):
    lines = []
    ts, te = e["text_start"], e["text_end"]
    if ts is None:
        lines.append("      - [0x0, data]")
    else:
        if ts > 0:
            lines.append("      - [0x0, data]")
        lines.append(f"      - [0x{ts:X}, asm]")
        if te < e["part2_size"]:
            lines.append(f"      - [0x{te:X}, data]")
    return "\n".join(lines)


def main():
    codemap = json.load(open(os.path.join(OVERLAYS, "codemap.json")))
    template = open(TEMPLATE).read()
    toml = [
        "# Silent Bomber DATA.BIN package overlay manifest - GENERATED by",
        "# decomp/tools/gen_overlay_configs.py from codemap.json; do not edit by hand.",
        "#",
        "# One entry per package part2 (the code-bearing part). part1 is a",
        "# bundle of TIMs, part3 is QMD model/scene data - neither contains",
        "# MIPS code. Load addresses: 0x800DD4F0 for every package loaded by",
        "# the generic loader func_80012E10 (destination D_800B5BB8, written",
        "# once at boot at 0x8001015C); ARENAP loads at 0x801A0000 via its own",
        "# loader thread (constant at 0x80017790). Both VERIFIED by disassembly",
        "# and by j/jal target analysis against each overlay's code.",
        "",
        "[packages]",
    ]
    for name, e in sorted(codemap.items()):
        yaml = template
        text = "data-only" if e["text_start"] is None else \
            f"text=0x{e['text_start']:X}..0x{e['text_end']:X}"
        repl = {
            "@@TITLE@@": TITLES.get(name, name),
            "@@NAME@@": name,
            "@@TARGET@@": f"assets/USA/packages/{name}.part2.bin",
            "@@VRAM@@": f"0x{e['vram']:08X}",
            "@@SIZE_HEX@@": f"0x{e['part2_size']:X}",
            "@@SIZE@@": str(e["part2_size"]),
            "@@SHA1@@": e["sha1_part2"],
            "@@SUBSEGMENTS@@": subsegments(e),
        }
        for k, v in repl.items():
            yaml = yaml.replace(k, v)
        with open(os.path.join(OVERLAYS, f"{name}.yaml"), "w") as f:
            f.write(yaml)
        toml += [
            "",
            f"[packages.{name}]",
            f'title = "{TITLES.get(name, name)}"',
            f"slot = {e['slot']}",
            f"file_off = 0x{e['file_off']:X}",
            f"vram = 0x{e['vram']:08X}",
            f"size = 0x{e['part2_size']:X}",
            f"w3 = 0x{e['w3']:X}   # live region: header/strings + .text + rodata",
            f"w4 = 0x{e['w4']:X}   # registration records (func_80012D34 pass)",
            f"w5 = 0x{e['w5']:X}   # read then overwritten by the part3 load",
            f"part3_size = 0x{e['part3_size']:X}",
            f"tim_blocks = {e['tim_blocks']}",
            f'text = "{text}"',
            f'sha1 = "{e["sha1_part2"]}"',
        ]
    with open(os.path.join(OVERLAYS, "overlays.toml"), "w") as f:
        f.write("\n".join(toml) + "\n")
    print(f"generated {len(codemap)} configs + overlays.toml in {OVERLAYS}")


if __name__ == "__main__":
    main()
